import { GameWord } from './interfaces';

// Array of all the words that is to be predicted.
export const gameData: Array<GameWord> = [
    {
        index: 1,
        word: 'HIP',
        clue: 'A cheerful start (3)',
        row: 1,
        col: 1,
        dir: 'horizontal',
    },
    {
        index: 2,
        word: 'IRATE',
        clue: 'Angry Irish rebels? (5)',
        row: 1,
        col: 2,
        dir: 'vertical',
    },
    {
        index: 3,
        word: 'PUT',
        clue: 'Have a shot at an Olympic event (3)',
        row: 1,
        col: 3,
        dir: 'vertical',
    },
    {
        index: 4,
        word: 'RUBY',
        clue: "She's a jewel (4)",
        row: 2,
        col: 2,
        dir: 'horizontal',
    },
    {
        index: 5,
        word: 'YARD',
        clue: "A measure of one's back garden (4)",
        row: 2,
        col: 5,
        dir: 'vertical',
    },
    {
        index: 6,
        word: 'RAT',
        clue: "No, it's Polonius (3)",
        row: 3,
        col: 1,
        dir: 'horizontal',
    },
    {
        index: 6,
        word: 'RE',
        clue: "What's this all about? (2)",
        row: 3,
        col: 1,
        dir: 'vertical',
    },
    {
        index: 7,
        word: 'AN',
        clue: 'An article (2)',
        row: 3,
        col: 5,
        dir: 'horizontal',
    },
    {
        index: 8,
        word: 'ET',
        clue: 'A visitor from outside fills this space (2)',
        row: 4,
        col: 1,
        dir: 'horizontal',
    },
    {
        index: 9,
        word: 'OR',
        clue: "What's the alternative? (2)",
        row: 4,
        col: 4,
        dir: 'horizontal',
    },
    {
        index: 9,
        word: 'OO',
        clue: "The printer hasn't got my number (2)",
        row: 4,
        col: 4,
        dir: 'vertical',
    },
    {
        index: 10,
        word: 'ERODE',
        clue: "Dick Turpin did this to York: it wore 'im out (5)",
        row: 5,
        col: 2,
        dir: 'horizontal',
    },
];
